apiVersion: zeabur.com/v1
kind: Template
metadata:
    name: mc-on-zeabur
spec:
    description: 在 Zeabur 設定 Paper MC 的麥塊伺服器，不必要在設置一台伺服器．
    icon: https://www.minecraft.net/etc.clientlibs/minecraftnet/clientlibs/clientlib-site/resources/favicon.ico
    variables:
        - key: USER_AUTHORIZATION
          type: STRING
    tags:
        - Minecraft
        - PaperMC
    volumes:
        - id: data
          dir: /data
    readme: 在 Zeabur 設定 Paper MC 的麥塊伺服器，不必要在設置一台伺服器．
    services:
        - name: paper-mc
          icon: https://www.minecraft.net/etc.clientlibs/minecraftnet/clientlibs/clientlib-site/resources/favicon.ico
          template: PREBUILT
          spec:
            source:
                image: marctv/minecraft-papermc-server:latest
            ports:
                - id: mc
                  port: 25565
                  type: TCP
            env:
                TZ:
                    default: Asia/Taipei
                MEMORYSIZE:
                    default: 1G
